[tox]
envlist = py3.11, py3.12, py3.13

[testenv]
basepython =
    py3.11: python3.11
    py3.12: python3.12
    py3.13: python3.13
setenv =
    PYTHONPATH = {toxinidir}
deps =
    {toxinidir}
    -r{toxinidir}/requirements_dev.txt
commands =
    pytest --basetemp={envtmpdir}
